# Generated by Django 3.2.6 on 2021-09-19 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_requirement',
            field=models.TextField(max_length=1024, verbose_name='职位要求'),
        ),
    ]
