# Generated by Django 3.2.6 on 2021-09-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(blank=True, null=True, unique=True, verbose_name='应聘者ID')),
                ('username', models.CharField(max_length=100, verbose_name='姓名')),
                ('city', models.CharField(max_length=100, verbose_name='城市')),
                ('phone', models.CharField(max_length=100, verbose_name='手机号码')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='邮箱')),
                ('apply_position', models.CharField(blank=True, max_length=100, verbose_name='应聘职位')),
                ('born_address', models.CharField(blank=True, max_length=100, verbose_name='生源地')),
                ('gender', models.CharField(blank=True, max_length=100, verbose_name='性别')),
                ('candidate_remark', models.CharField(blank=True, max_length=100, verbose_name='候选人信息备注')),
                ('bachelor_school', models.CharField(blank=True, max_length=100, verbose_name='本科学校')),
                ('master_school', models.CharField(blank=True, max_length=100, verbose_name='硕士学校')),
                ('doctor_school', models.CharField(blank=True, max_length=100, verbose_name='博士学校')),
                ('major', models.CharField(blank=True, max_length=100, verbose_name='专业')),
                ('degree', models.CharField(blank=True, choices=[('BACHELOR', '本科'), ('MASTER', '硕士'), ('DOCTOR', '博士')], max_length=100, verbose_name='学历')),
                ('comprehensive_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='综合能力测评得分')),
                ('paper_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='笔试得分')),
                ('first_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='一面得分')),
                ('first_score_learning', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='学习能力得分')),
                ('first_score_professional', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业能力得分')),
                ('first_advantage', models.TextField(blank=True, max_length=1000, verbose_name='优势')),
                ('first_disadvantage', models.TextField(blank=True, max_length=1000, verbose_name='顾虑和不足')),
                ('first_result', models.CharField(blank=True, choices=[('PASS', '建议复试'), ('UNDETERMINED', '待定'), ('DROP', '放弃')], max_length=100, verbose_name='一面结果')),
                ('first_recommend_position', models.CharField(blank=True, max_length=100, verbose_name='推荐部门')),
                ('first_interviewer', models.CharField(blank=True, max_length=100, verbose_name='面试官')),
                ('first_remark', models.CharField(blank=True, max_length=100, verbose_name='一面备注')),
                ('second_score', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='二面得分')),
                ('second_score_learning', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='学习能力得分')),
                ('second_score_professional', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='专业能力得分')),
                ('second_score_excellent', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='追求卓越得分')),
                ('second_score_communication', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='沟通能力得分')),
                ('second_score_anti_pressure', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='抗压能力得分')),
                ('second_advantage', models.TextField(blank=True, max_length=1000, verbose_name='优势')),
                ('second_disadvantage', models.TextField(blank=True, max_length=1000, verbose_name='顾虑和不足')),
                ('second_result', models.CharField(blank=True, choices=[('PASS', '建议录用'), ('UNDETERMINED', '待定'), ('DROP', '放弃')], max_length=100, verbose_name='二面结果')),
                ('second_recommend_position', models.CharField(blank=True, max_length=100, verbose_name='建议方向或推荐部门')),
                ('third_score', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='三面评级')),
                ('third_score_responsibility', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='责任心评级')),
                ('third_score_communication', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='坦诚沟通评级')),
                ('third_score_logic', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='逻辑思维评级')),
                ('third_score_potential', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='发展潜力评级')),
                ('third_score_stability', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10, verbose_name='稳定性评级')),
                ('third_advantage', models.TextField(blank=True, max_length=1000, verbose_name='优势')),
                ('third_disadvantage', models.TextField(blank=True, max_length=1000, verbose_name='顾虑和不足')),
                ('third_result', models.CharField(blank=True, choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100, verbose_name='三面结果')),
                ('second_interviewer', models.CharField(blank=True, max_length=100, verbose_name='面试官')),
                ('second_remark', models.CharField(blank=True, max_length=100, verbose_name='三面备注')),
                ('creator', models.CharField(blank=True, max_length=100, verbose_name='候选人创建人')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modified_date', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('last_editor', models.CharField(blank=True, max_length=100, verbose_name='最后编辑者')),
            ],
            options={
                'verbose_name': '应聘者',
                'verbose_name_plural': '应聘者',
                'db_table': 'candidate',
            },
        ),
    ]
