# Generated by Django 3.2.6 on 2021-09-21 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='third_interviewer',
            field=models.CharField(blank=True, max_length=100, verbose_name='面试官'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='third_remark',
            field=models.TextField(blank=True, max_length=1000, verbose_name='三面备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='candidate_remark',
            field=models.TextField(blank=True, max_length=1000, verbose_name='候选人信息备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='first_remark',
            field=models.TextField(blank=True, max_length=1000, verbose_name='一面备注'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_remark',
            field=models.TextField(blank=True, max_length=1000, verbose_name='二面备注'),
        ),
    ]
